FROM node:20-slim

# Diretório de trabalho
WORKDIR /app

# Copiar e instalar dependências do Node.js
COPY package.json package-lock.json ./
RUN npm install

# Copiar o restante do código
COPY . .

# Construir a aplicação Angular
RUN npm run build

# Expor a porta do Angular
EXPOSE 4200

# Comando padrão para rodar o frontend
CMD ["npx", "http-server", "dist"]