FROM python:3.12-slim

# Instalar dependências do sistema para PostgreSQL e compiladores
RUN apt-get update && apt-get install -y \
    libpq-dev gcc && \
    apt-get clean

# Diretório de trabalho
WORKDIR /app

# Copiar e instalar dependências do Python
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copiar o código do projeto
COPY . .

# Expor a porta padrão do Django
EXPOSE 8000

# Comando padrão para rodar o backend
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]